tools:
  - name: "get_assistant"
    description: "Answers questions related to CloudForge products"
    url: "http://a8e66c107696f4ba98c48cee392d6fc8-419097757.us-east-2.elb.amazonaws.com/query"
    config:
      method: 'POST'
      headers:
        'Content-Type': 'application/json'
      body:
        query_text: '{{prompt}}'
        top_k: 3
      responseParser: 'text_chunk'
      responseFormat:
        agent: '{{response}}'
        json:
          - "response"
      examples:
        - "What is the AI Optimizer product?"