apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-standalone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
    spec:
      containers:
        - name: milvus-standalone
          image: milvusdb/milvus:v2.4.13-hotfix
          command: ["milvus", "run", "standalone"]
          env:
            - name: ETCD_USE_EMBED
              value: "true"
            - name: ETCD_DATA_DIR
              value: "/var/lib/milvus/etcd"
            - name: ETCD_CONFIG_PATH
              value: "/milvus/configs/embedEtcd.yaml"
            - name: COMMON_STORAGETYPE
              value: "local"
          ports:
            - containerPort: 19530
            - containerPort: 9091
            - containerPort: 2379
          volumeMounts:
            - name: milvus-volume
              mountPath: /var/lib/milvus
            - name: config-embedetcd
              mountPath: /milvus/configs/embedEtcd.yaml
              subPath: embedEtcd.yaml
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9091
            initialDelaySeconds: 90
            periodSeconds: 30
            timeoutSeconds: 20
            failureThreshold: 3
      volumes:
        - name: milvus-volume
          emptyDir: {}
        - name: config-embedetcd
          configMap:
            name: embedetcd-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: embedetcd-config
data:
  embedEtcd.yaml: |
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://0.0.0.0:2379
    quota-backend-bytes: 4294967296
    auto-compaction-mode: revision
    auto-compaction-retention: '1000'
---
apiVersion: v1
kind: Service
metadata:
  name: milvus-service
spec:
  selector:
    app: milvus
  ports:
    - name: grpc
      protocol: TCP
      port: 19530
      targetPort: 19530
    - name: http
      protocol: TCP
      port: 9091
      targetPort: 9091
    - name: etcd
      protocol: TCP
      port: 2379
      targetPort: 2379
  type: LoadBalancer

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: milvus-route
spec:
  to:
    kind: Service
    name: milvus-service
  port:
    targetPort: http
